services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_INIT_LIMIT: 5
    ports:
      - "2181:2181"
    networks:
      - kafka_net 
    volumes:
      - zookeeper-data:/var/lib/zookeeper
      - zookeeper-log:/var/log/zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # Adjust if needed
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Set this to the number of brokers if scaling
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1  # Minimum in-sync replicas
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168  # Retain logs for 7 days
      KAFKA_LOG_SEGMENT_BYTES: 1073741824  # 1GB segment size
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'  # Disable automatic topic creation for control
    networks:
      - kafka_net
    volumes:
      - kafka-data:/var/lib/kafka/data
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    ulimits:
      nofile:
        soft: 100000
        hard: 100000

volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
  kafka-data:
    driver: local

networks:
  kafka_net:
    name: kafka_net
    driver: bridge

